### ISSUE TITLE
Fails to build in IntelliJ 15.0.2

### ISSUE THREAD

**Issue by chanster** [libgdx/libgdx-demo-cuboc#8]
When applying work around stated here:
http://www.badlogicgames.com/forum/viewtopic.php?p=87771&sid=007f72ddbc7f4acf7477522b6dd58c6d#p87771

IntelliJ errors with:

Module "android"
must not contain source root "/home/chanster/projects/libgdx/cuboc/android/src".
The root already belongs to module "android"

**Comment by MobiDevelop** [comment]
IDE bugs are not valid issues on projects.
